In [2]:
import pandas as pd

In [7]:
data = pd.read_csv('test.txt',header=None,dtype=object)
data_matrix = data.values
print(data_matrix)

[['A2' 'B1' 'C3' 'D3' 'E1' 'F1' 'H1']
 ['A2' 'B1' 'C3' 'D3' 'E1' 'F1' 'H1']
 ['A2' 'B1' 'C3' 'D3' 'E1' 'F1' 'H1']
 ['A2' 'B1' 'C3' 'D3' 'E1' 'F1' 'H1']
 ['A2' 'B2' 'C3' 'D3' 'E1' 'F1' 'H1']
 ['A1' 'B2' 'C1' 'D1' 'E1' 'F1' 'H1']
 ['A1' 'B1' 'C1' 'D1' 'E1' 'F1' 'H1']
 ['A1' 'B2' 'C1' 'D1' 'E1' 'F1' 'H1']
 ['A1' 'B2' 'C1' 'D1' 'E1' 'F1' 'H1']
 ['A1' 'B2' 'C1' 'D1' 'E1' 'F1' 'H1']
 ['A1' 'B2' 'C1' 'D3' 'E2' 'F1' 'H2']
 ['A3' 'B2' 'C1' 'D2' 'E3' 'F1' 'H2']]

In [10]:
ct = lambda x : pd.Series(1,index = x)
arrary = list(map(ct,data_matrix))
input_arrary = pd.DataFrame(arrary).fillna(0)
input_arrary = (input_arrary == 1)

In [11]:
input_arrary

,A2,B1,C3,D3,E1,F1,H1,B2,A1,C1,D1,E2,H2,A3,D2,E3
0,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False
1,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False
2,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False
3,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False
4,True,False,True,True,True,True,True,True,False,False,False,False,False,False,False,False
5,False,False,False,False,True,True,True,True,True,True,True,False,False,False,False,False
6,False,True,False,False,True,True,True,False,True,True,True,False,False,False,False,False
7,False,False,False,False,True,True,True,True,True,True,True,False,False,False,False,False
8,False,False,False,False,True,True,True,True,True,True,True,False,False,False,False,False
9,False,False,False,False,True,True,True,True,True,True,True,False,False,False,False,False
10,False,False,False,True,False,True,False,True,True,True,False,True,True,False,False,False
11,False,False,False,False,False,True,False,True,False,True,False,False,True,True,True,True

In [13]:
support = 0.06 
confidence = 0.75 
ms = '--'

In [14]:
def connect_string(x, ms):
    fun = lambda i:sorted(i.split(ms)) # [B--C,B--D,B--E]
    x = list(map(fun, x)) # [[B,C],[B,D],[B,E]]
    l = len(x[0]) # 2 in example
    r = []
    for i in range(len(x)):
        for j in range(i,len(x)):
            #[B,C] and [B,D] => [B,C,D]
            if x[i][:l-1] == x[j][:l-1] and x[i][l-1] != x[j][l-1]:
                r.append(x[i][:l-1]+sorted([x[j][l-1],x[i][l-1]]))
    return r